### PR TITLE
Updated README: IntelliJ now supports ligatures;

### PR DESCRIPTION
**Pull request by bdalenoord**
I've tested Hasklig in IntelliJ and switched to it as it works fine!

### CODE REVIEW

**Comment by LCastr0** [comment]
The != doesn't work :/

**Comment by bdalenoord** [comment]
It isn't in the list of supported symbols, so I suppose that could be expected?

**Comment by LCastr0** [comment]
Yes, but they could add it, maybe? It's a great font, I really wanna use it, but I'd like that symbol too :P I hope they add it

**Comment by i-tu** [comment]
Thank you for your contribution @bdalenoord !
Your RFE is noted @LCastr0 :)

**Pull request merged**
